blank_issues_enabled: false
contact_links:
    - name: Feature Requests & Questions
      url: https://github.com/kinkwilde/KEAIRA-BELL-MH0000001/discussions
      about: Ask anything that isn't bug or error related here.
